### PR TITLE
Updating 110718 event

### PR DESCRIPTION
**Pull request by gregboyer**
Updating with correct agenda and linkedin links, as well as schedule for open council meeting

### CODE REVIEW

**Review by jszwedko — APPROVED** [review]
Looks good!

Once the open leadership council agenda is created, you can add it over here: https://github.com/sfbrigade/codeforsanfrancisco.org/blob/master/_data/leadership-councils.yml#L1 (populates the table here: https://codeforsanfrancisco.org/about/leadership-council/).

**Comment by ProLoser** [comment]
@jszwedko This seems like it should be more automated.

**Comment by gregboyer** [comment]
I’ll create a task to check in on the Netlify automation. It was an easy
but manual refresh to get that out there.

- Greg

On Nov 5, 2018, at 10:05 AM, Dean Sofer <notifications@github.com> wrote:

@jszwedko <https://github.com/jszwedko> This seems like it should be more
automated, as it's creating a bit of manual work for us to maintain.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sfbrigade/codeforsanfrancisco.org/pull/32#issuecomment-435974109>,
or mute the thread

**Comment by jszwedko** [comment]
:+1:

Also one option we had previously discussed was nixing the pages in Jekyll and dynamically generating the event list and event pages based on Meetup's API.

At the least, you could generate a bunch and setup a nightly rebuild. That would alleviate the issue of the next event not automatically updating.

**Comment by jszwedko** [comment]
(but yes, this is clearly the place for automation :smile: )

**Pull request merged**
